add mypy typecheck to build.yaml

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -40,3 +40,24 @@ jobs:
         uses: codecov/codecov-action@v4
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+  typecheck-code:
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        include:
+          - python-version: "3.14"
+    steps:
+      - name: Checkout source repo
+        uses: actions/checkout@v4
+      - name: Setup Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Pip install --group typing
+        run: pip install --group typing
+      - name: Run mypy
+        run: |
+          FAILED=0
+          python -m mypy || FAILED=$?
+          [ $FAILED -eq 0 ] || echo "::warning::mypy failed with exit code $FAILED"
+        shell: bash
